<<: !include common_defaults.yaml

wifi:
  networks:
    - ssid: !secret wifi_ssid
      password: !secret wifi_password
    - ssid: !secret wifi_alternative_ssid
      password: !secret wifi_password
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${id} Fallback Hotspot"
    password: !secret hotspot_password

ota:
  - platform: esphome
    password: !secret ota_password

captive_portal:

sensor:
  - platform: wifi_signal
    name: "WIFI RSSI"
    id: wifi_sensor_rssi
    update_interval: 60s
    entity_category: "diagnostic"

text_sensor:
  - platform: wifi_info
    ip_address:
      id: wifi_ip_address
      name: WIIF IP Address
      icon: "mdi:wan"
      entity_category: "diagnostic"
    ssid:
      id: wifi_ssid
      name: WIFI SSID
      entity_category: "diagnostic"
    bssid:
      id: wifi_bssid
      name: WIFI BSSID
      icon: "mdi:wan"
      entity_category: "diagnostic"
