substitutions:
  id: ${id}
  friendly_name: ${name}
  blink_switch_id: dummy_switch_id
  blink_interval: "500ms"

wifi:
  on_disconnect:
    then:
      - logger.log:
          level: DEBUG
          format: "Wifi disconnected, starting to blink ${blink_switch_id}"
      - while:
          condition:
            not: wifi.connected
          then:
            - switch.toggle: ${blink_switch_id}
            - delay: "${blink_interval}"
  on_connect:
    then:
      - switch.turn_off: ${blink_switch_id}
      - logger.log:
          level: DEBUG
          format: "Blinking will now be disabled because WiFi has reconnected"



