# feature that offers a winddown (go to sleep) function
substitutions:
  sleep_id: sleepmode
  sleep_friendly_name: Sleep Mode
  sleepmode_engage_callback_script: ${sleep_id}_dummy_script

globals:
  - id: ${sleep_id}_last_engaged
    type: time_t
    restore_value: no
    initial_value: '0'

switch:
  - platform: template
    name: ${sleep_friendly_name} Engaged
    id: ${sleep_id}_engaged
    icon: mdi:sleep
    optimistic: true
    on_turn_off:
      - script.stop: ${sleep_id}_sleepmode_check
    on_turn_on:
      - globals.set:
          id: ${sleep_id}_last_engaged
          value: !lambda "return id(ha_time).now().timestamp;"
      - lambda: |-
          int delay = (int)id(${sleep_id}_delay_minutes).state;
          time_t target = (id(${sleep_id}_last_engaged) + (delay * 60));
          ESP_LOGD("sleep", "Sleep mode engaged at %d", id(ha_time).now());
          ESP_LOGD("sleep", "After delay of %dmins device will activate sleep sequence at %d ..", delay, (int) target );
      - script.stop: ${sleep_id}_sleepmode_check
      - script.execute: ${sleep_id}_sleepmode_check

number:
  - platform: template
    id: ${sleep_id}_delay_minutes
    name: ${sleep_friendly_name} delay minutes
    icon: mdi:timer-cog-outline
    step: 10
    min_value: 1
    max_value: 1440
    initial_value: 30
    mode: box
    entity_category: config
    restore_value: true
    optimistic: true

script:
  - id: ${sleep_id}_dummy_script
    then:
      - logger.log: 
          format: SLEEPMODE DUMMY SCRIPT EXECUTED. Please pass a script to this package as var to replace this function.
          tag: sleep
  - id: ${sleep_id}_execute_sleep_function
    then:
      - logger.log: 
          format: executing sleep function
          tag: sleep
      - lambda: |-
          id(${sleep_id}_engaged).publish_state(false);
      - script.execute: ${sleepmode_engage_callback_script}
  - id: ${sleep_id}_sleepmode_check
    then:
      - while:
          condition:
            switch.is_on: ${sleep_id}_engaged
          then:
            - if:
                condition:
                  - lambda: 'return ( id(ha_time).now().timestamp >= (id(${sleep_id}_last_engaged) + ((int)id(${sleep_id}_delay_minutes).state * 60)) );'
                then:
                  - script.execute: ${sleep_id}_execute_sleep_function
            - delay: 10 min
