# feature that offers a winddown (go to sleep) function
substitutions:
  sleepmode_engage_callback_script: sleepmode_dummy_script

globals:
  - id: sleepmode_last_engaged
    type: time_t
    restore_value: no
    initial_value: '0'

switch:
  - platform: template
    name: Sleep Mode Engaged
    id: sleepmode_engaged
    optimistic: true
    on_turn_off:
      - script.stop: sleepmode_check
    on_turn_on:
      - globals.set:
          id: sleepmode_last_engaged
          value: !lambda "return id(ha_time).now().timestamp;"
      - lambda: |-
          int delay = (int)id(sleep_delay_minutes).state;
          time_t target = (id(sleepmode_last_engaged) + (delay * 60));
          ESP_LOGD("sleep", "Sleep mode engaged at %d", id(ha_time).now());
          ESP_LOGD("sleep", "After delay of %dmins device will activate sleep sequence at %d ..", delay, (int) target );
      - script.stop: sleepmode_check
      - script.execute: sleepmode_check

number:
  - platform: template
    id: sleep_delay_minutes
    name: sleep delay minutes
    step: 1
    min_value: 1
    max_value: 1440
    initial_value: 30
    mode: box
    entity_category: config
    restore_value: true
    optimistic: true

script:
  - id: sleepmode_dummy_script
    then:
      - logger.log: 
          format: SLEEPMODE DUMMY SCRIPT EXECUTED. Please pass a script to this package as var to replace this function.
          tag: sleep
  - id: sleepmode_execute_sleep_function
    then:
      - logger.log: 
          format: executing sleep function
          tag: sleep
      - lambda: |-
          id(sleepmode_engaged).publish_state(false);
      - script.execute: ${sleepmode_engage_callback_script}
  - id: sleepmode_check
    then:
      - while:
          condition:
            switch.is_on: sleepmode_engaged
          then:
            - if:
                condition:
                  - lambda: 'return ( id(ha_time).now().timestamp >= (id(sleepmode_last_engaged) + ((int)id(sleep_delay_minutes).state * 60)) );'
                then:
                  - script.execute: sleepmode_execute_sleep_function
            - delay: 10 min
