substitutions:
  sensor_id: bme280
  sensor_friendly_name: "BME 280"
  i2c_bus_id: ${id}_bus_a
  i2c_address: "0x76"
  update_interval: "60s"

# Description: This file contains the configuration for the BME280 sensor connected via I2C.
sensor:  
  - platform: bme280_i2c
    i2c_id: ${i2c_bus_id}
    temperature:
      name: Temperature
      id: ${sensor_id}_temperature
      oversampling: 16x
    pressure:
      name: Pressure
      id: ${sensor_id}_pressure
    humidity:
      name: Humidity
      id: ${sensor_id}_humidity
    address: ${i2c_address}
    update_interval: ${update_interval}